alertmanager:
  alertmanagerSpec:

    # AlertmanagerConfig objects in the Alertmanager namespace
    # may process alerts originating from other namespaces.
    alertmanagerConfigMatcherStrategy:
      type: OnNamespaceExceptForAlertmanagerNamespace

