apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: production-cloud-platform
  namespace: argocd

spec:
  destination:
    namespace: telemetry-system
    server: https://kubernetes.default.svc

  project: default

  source:
    path: helm/production-cloud-platform
    repoURL: https://github.com/av-crypto-security/production-cloud-platform.git
    targetRevision: main

  syncPolicy:
    automated:
      selfHeal: true
