apiVersion: v1
kind: ConfigMap
metadata:
  name: telemetry-config
  namespace: {{ .Release.Namespace }}
data:
  POSTGRES_HOST: {{ .Values.postgres.host | quote }}
  POSTGRES_DB: {{ .Values.postgres.database | quote }}
