apiVersion: batch/v1
kind: Job
metadata:
  name: telemetry-db-migration
  namespace: {{ .Release.Namespace }}
  annotations:
    argocd.argoproj.io/hook: Sync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation,HookSucceeded
    argocd.argoproj.io/sync-wave: "0"
spec:
  backoffLimit: 2
  activeDeadlineSeconds: 300
  template:
    metadata:
      labels:
        app: telemetry-db-migration
    spec:
      restartPolicy: Never
      containers:
        - name: database-migration
          image: "{{ .Values.processing.image.repository }}:{{ .Values.processing.image.tag }}"
          imagePullPolicy: IfNotPresent
          command:
            - alembic
            - upgrade
            - head
          env:
            - name: POSTGRES_HOST
              valueFrom:
                configMapKeyRef:
                  name: telemetry-config
                  key: POSTGRES_HOST
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: telemetry-config
                  key: POSTGRES_DB
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: telemetry-secret
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: telemetry-secret
                  key: POSTGRES_PASSWORD
