apiVersion: v1
kind: Service
metadata:
  name: postgres-exporter
  namespace: {{ .Release.Namespace }}
  labels:
    app: postgres-exporter
spec:
  selector:
    app: postgres-exporter
  ports:
    - name: metrics
      port: {{ .Values.postgresExporter.service.port }}
      targetPort: metrics
      protocol: TCP
  type: ClusterIP
