apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  RABBITMQ_DEFAULT_USER: {{ .Values.rabbitmq.auth.username | quote }}
  RABBITMQ_DEFAULT_PASS: {{ .Values.rabbitmq.auth.password | quote }}
  RABBITMQ_USER: {{ .Values.rabbitmq.auth.username | quote }}
  RABBITMQ_PASSWORD: {{ .Values.rabbitmq.auth.password | quote }}
