apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-headless
  namespace: {{ .Release.Namespace }}
  labels:
    app: rabbitmq
spec:
  clusterIP: None
  publishNotReadyAddresses: true
  ports:
    - name: amqp
      port: 5672
      targetPort: amqp
    - name: management
      port: 15672
      targetPort: management
    - name: metrics
      port: 15692
      targetPort: metrics
  selector:
    app: rabbitmq
