apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: rabbitmq
  namespace: {{ .Release.Namespace }}
spec:
  serviceName: rabbitmq-headless
  replicas: {{ .Values.rabbitmq.replicaCount }}
  selector:
    matchLabels:
      app: rabbitmq

  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
        - name: rabbitmq
          image: "{{ .Values.rabbitmq.image.repository }}:{{ .Values.rabbitmq.image.tag }}"
          imagePullPolicy: {{ .Values.rabbitmq.image.pullPolicy }}

          envFrom:
            - secretRef:
                name: rabbitmq-secret

          ports:
            - name: amqp
              containerPort: 5672

            - name: management
              containerPort: 15672

            - name: metrics
              containerPort: 15692

          resources:
{{ toYaml .Values.rabbitmq.resources | indent 12 }}

          volumeMounts:
            - name: rabbitmq-data
              mountPath: /var/lib/rabbitmq

          livenessProbe:
            exec:
              command:
                - rabbitmq-diagnostics
                - -q
                - ping
            initialDelaySeconds: 30
            periodSeconds: 20
            timeoutSeconds: 5
            failureThreshold: 3

          readinessProbe:
            exec:
              command:
                - rabbitmq-diagnostics
                - -q
                - ping
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3

  volumeClaimTemplates:
    - metadata:
        name: rabbitmq-data
      spec:
        accessModes:
          - ReadWriteOnce
        storageClassName: {{ .Values.rabbitmq.persistence.storageClass }}
        resources:
          requests:
            storage: {{ .Values.rabbitmq.persistence.size }}
