apiVersion: v1
kind: Secret
metadata:
  name: telemetry-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  POSTGRES_USER: {{ .Values.postgres.user | quote }}
  POSTGRES_PASSWORD: {{ .Values.postgres.password | quote }}
