ingestion:
  replicaCount: 2
  image:
    repository: ghcr.io/av-crypto-security/ingestion-api
    tag: v1.0.0

processing:
  replicaCount: 1
  image:
    repository: ghcr.io/av-crypto-security/processing-service
    tag: v1.0.1

simulator:
  replicaCount: 1
  image:
    repository: ghcr.io/av-crypto-security/simulator
    tag: v1.0.0

postgres:
  image:
    repository: postgres
    tag: "16"
  storage: 10Gi


  host: postgres-service
  database: telemetry


  user: postgres
  password: postgres
