name: Build and Push Docker Images


on:
  push:
    branches:
      - main


permissions:
  contents: read
  packages: write


jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses:  actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push ingestion-api
        uses: docker/build-push-action@v6
        with:
          context: ./services/ingestion-api
          push: true
          tags: |
            ghcr.io/av-crypto-security/ingestion-api:v1.0.0
            ghcr.io/av-crypto-security/ingestion-api:latest
